### ISSUE TITLE
Heroku 16 stack fails to render pdf after ~5 minutes post restart

### ISSUE THREAD

**Issue by chughes** [dscout/wkhtmltopdf-buildpack#35] opened 2019-02-26 16:49 UTC
Heroku released an update to its Heroku 16 stack on December 18. Since that update to our Heroku instances, pdf rendering will only temporarily work on a new branch deploy or instance restart. After ~5 mins pdf rendering silently fails (ie. no information presented in log file).

Final log entry is:
2019-02-01T17:37:56.044912+00:00 app[web.1]: _**************WICKED**************_

That is followed by a series of rack-timeout notifications until we reach the Heroku limit and the call fails.
2019-02-01T17:37:58.588912+00:00 app[web.1]: source=rack-timeout id=511db688-876f-4b5d-bb58-2a52f749509f wait=3ms timeout=28000ms service=3000ms state=active
2019-02-01T17:37:59.588844+00:00 app[web.1]: source=rack-timeout id=511db688-876f-4b5d-bb58-2a52f749509f wait=3ms timeout=28000ms service=4000ms state=active
...

Spoke with Heroku support and they redirected me to post here.

rails 4.2.11
ruby 2.2.7
wicked_pdf 1.1.0
puma 3.11.3

**Comment by sorentwo** [comment] 2019-03-06 01:00
We've encountered this in the pack and discovered that rendering some HTML will cause wkhtmltopdf to cause a kernel panic and crash the dyno without any logging. After lengthy attempts to diagnose the root cause we moved on to chrome-headless and use that for all of our PDF rendering.

I'm going to close this as something that we can't fix. Sorry for your troubles!

**Closed as completed by sorentwo** 2019-03-06 01:00 UTC
